### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by yourh3ro** [Shenor/driver-SHTRIH-PRINT#1]
Этот сервер занимается загрузкой весов по формату ШТРИХ ПРИНТ? 
Напишите пожалуйста, документацию. Как работать с этим сервером?

**Comment by Shenor** [comment]
Драйвер был создан для выгрузки номенклатуры товаров с системы R-keeper в формате xml и загрузки ее в ПЛУ весов Штрих-Принт, так как система R-keeper не имеет прямой интеграции с весами. Поэтому данное решение было написано индивидуально под клиента и не имеет широкого функционала. Принцип действия прост: 

1. При выгрузке номенклатуры из системы R-keeper создается файл формата xml.
2. Далее необходимо перенести файл в корневую директорию с программой, переименовать `scale.xml` его в  и запустить `RUN.BAT`. Далее скрипт автоматически выгрузит данные из xml файла выгруженного исключительно из системы R-keeper.

**Примечание:** Так как решение писалось индивидуально опишу некоторые важные моменты. Весы подключены по Ethernet, поэтому необходимо будет либо в настройках весов изменить адрес на `192.168.1.202:1111` который указан по умолчанию в скрипте, либо поменять connection string #https://github.com/Shenor/driver-SHTRIH-PRINT/blob/master/server.js#L11
На весах так же был установлен пароль и при передачи команд необходимо было его передавать. Решение такое либо установить на свои весы пароль такой же как задан по умолчанию, либо заменить его просто в коде на вам необходимый https://github.com/Shenor/driver-SHTRIH-PRINT/blob/master/server.js#L82.
